name: CI
on:
    pull_request:
    push:
      branches:
        - main

permissions:
  contents: read
  packages: read
  # To report GitHub Actions status checks
  statuses: write


jobs:
  
  build:
    strategy:
        matrix:
          node-version: ["21.x", "20.x"]
      
    runs-on: ubuntu-latest
    steps:
        
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
              .github
              src
              __tests__
      - uses: actions/setup-node@v4
        
        with:
            node-version: ${{ matrix.node-version }}
            check-latest: true
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      
    